//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANLYBENHVIEN
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONVIENPHI
    {
        public int MaHoaDon { get; set; }
        public Nullable<int> MaBenhNhan { get; set; }
        public Nullable<int> MaPhong { get; set; }
        public System.DateTime NgayNhapVien { get; set; }
        public Nullable<System.DateTime> NgayXuatVien { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual BENHNHAN BENHNHAN { get; set; }
        public virtual PHONGBENH PHONGBENH { get; set; }
    }
}
